[general]

[backup]
backup_dir = "C:\Users\Yannick\Documents\repos\Nextcloud_backup_script\backup"
regex = "\.tar\.gz\.gpg$"
password = "PASSWORD"

[create]
compress = true
encrypt = true
compression_command = "tar cfz %d %s"
encryption_command = "gpg --batch --yes -c --cipher-algo AES256 -o %d --passphrase '%p' %s"

[transfer]
user = "USER"
host = "HOSTNAME/IP"
port = 22
remote_dir = "/home/USER/backup"
uploaded_log = "uploaded.log"
identity_file = 
only_new = true

[purge]
keep = 7

[nextcloud]
docker = true
docker-compose_file = 
nextcloud_path = 
container_name = 